[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
fs_permissions = [{ access = "read", path = "./"}]
remappings = [
    '@root/=contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/'
]
